const Contents = () => {
    return(
        <div className="m-9 p-0 gap-4 text-[#484540] dark:text-white dark:bg-[#270E12] bg-[#270E12]">
            <h1 className="text-3xl font-bold mb-4">
                Hello world!
            </h1>
            <p className="p-4 mb-6">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce commodo felis nec bibendum iaculis. Sed porttitor pulvinar magna, quis imperdiet nunc gravida sit amet. Vivamus interdum vulputate nisl et consectetur. Duis fringilla velit quis laoreet blandit. Integer ultricies nunc quis metus blandit, ut posuere lectus posuere. Nunc eleifend risus ipsum, non sagittis nulla cursus vel. Cras id tincidunt arcu. Sed elementum turpis dictum egestas bibendum. Maecenas feugiat risus vel tempor porttitor. Nam et lorem hendrerit, aliquet erat ut, blandit mi. Praesent semper turpis nec tincidunt ornare. Nullam accumsan ornare ligula, eu tempor sem tristique pulvinar. Quisque a diam ut dui suscipit rhoncus et eget nisl. Vivamus sed enim vitae odio mattis malesuada. In scelerisque risus in ligula iaculis aliquet.</p>

            <p className="p-4 mb-6">Donec at tristique purus, sed scelerisque nisl. Proin accumsan suscipit hendrerit. Etiam id orci auctor, vulputate nisi id, consectetur augue. Nulla vestibulum, ante quis viverra condimentum, massa justo eleifend elit, id molestie sem justo ac risus. Etiam eu gravida sem. Duis tempus nisl quis ante sagittis vulputate. Donec sodales ipsum urna, ac dictum enim fringilla at. Curabitur eros ex, auctor eu leo sit amet, pharetra consectetur nibh. Ut neque mi, porta nec odio ac, dignissim cursus turpis. Nam ultricies semper nunc, eu scelerisque ipsum lacinia vitae. Praesent lorem velit, faucibus ut rutrum nec, finibus eu lacus. Sed consectetur ante arcu, eget finibus magna placerat et. Praesent imperdiet egestas magna eget consequat.</p>

            <p className="p-4 mb-6">Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Proin in tortor placerat, efficitur lacus ac, hendrerit tellus. Sed eu felis sed magna tincidunt cursus vel fermentum erat. Vivamus congue rhoncus velit, fringilla tempus mi volutpat eu. Donec eu malesuada odio. Praesent nec congue libero, ut feugiat odio. Aliquam volutpat, massa sed sodales ultricies, velit velit imperdiet justo, sit amet finibus est enim non lacus. Cras eu bibendum nunc. Duis sodales ligula et tincidunt blandit. Phasellus non luctus nisl. Nam vehicula risus ut nulla dapibus, ac interdum est consectetur. Pellentesque ac aliquet augue, id tempor nisl. Suspendisse potenti.</p>

            <p className="p-4 mb-6">Cras eget pulvinar risus. Phasellus blandit lectus a nisi pharetra congue. Mauris ornare nisi in pellentesque placerat. Fusce dignissim sem fringilla sapien sagittis tempus. Praesent vel fringilla turpis. Nulla facilisi. Integer faucibus metus tortor, sit amet aliquam ante tincidunt vitae. Mauris mattis a neque id fermentum. Nam cursus arcu a scelerisque blandit. Integer mollis in arcu quis finibus. Duis mattis, tortor vel fermentum rutrum, magna est malesuada odio, at porta mi ligula vel dui. Aliquam malesuada turpis eu dolor volutpat, in porttitor sapien dapibus.</p>

            <p className="p-4 mb-6">Donec aliquam porttitor hendrerit. Sed bibendum mauris velit, eu blandit ipsum condimentum ac. Suspendisse at auctor nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Sed tempus ultricies enim vitae efficitur. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris nec tincidunt tortor. Fusce faucibus congue lorem in bibendum. Donec vestibulum tincidunt mi, at posuere velit feugiat quis. Aliquam varius auctor magna a tincidunt. Donec in fermentum augue, quis volutpat nunc. Etiam metus lorem, ornare eu pellentesque in, tempor a augue. Vestibulum semper massa id odio bibendum, ac sollicitudin lacus bibendum.</p>

            <h1 className="text-3xl font-bold mb-4 text-center">
                Hello Again!
            </h1>
            <p className="p-4 mb-6">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce commodo felis nec bibendum iaculis. Sed porttitor pulvinar magna, quis imperdiet nunc gravida sit amet. Vivamus interdum vulputate nisl et consectetur. Duis fringilla velit quis laoreet blandit. Integer ultricies nunc quis metus blandit, ut posuere lectus posuere. Nunc eleifend risus ipsum, non sagittis nulla cursus vel. Cras id tincidunt arcu. Sed elementum turpis dictum egestas bibendum. Maecenas feugiat risus vel tempor porttitor. Nam et lorem hendrerit, aliquet erat ut, blandit mi. Praesent semper turpis nec tincidunt ornare. Nullam accumsan ornare ligula, eu tempor sem tristique pulvinar. Quisque a diam ut dui suscipit rhoncus et eget nisl. Vivamus sed enim vitae odio mattis malesuada. In scelerisque risus in ligula iaculis aliquet.</p>

            <p className="p-4 mb-6">Donec at tristique purus, sed scelerisque nisl. Proin accumsan suscipit hendrerit. Etiam id orci auctor, vulputate nisi id, consectetur augue. Nulla vestibulum, ante quis viverra condimentum, massa justo eleifend elit, id molestie sem justo ac risus. Etiam eu gravida sem. Duis tempus nisl quis ante sagittis vulputate. Donec sodales ipsum urna, ac dictum enim fringilla at. Curabitur eros ex, auctor eu leo sit amet, pharetra consectetur nibh. Ut neque mi, porta nec odio ac, dignissim cursus turpis. Nam ultricies semper nunc, eu scelerisque ipsum lacinia vitae. Praesent lorem velit, faucibus ut rutrum nec, finibus eu lacus. Sed consectetur ante arcu, eget finibus magna placerat et. Praesent imperdiet egestas magna eget consequat.</p>

            <p className="p-4 mb-6">Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Proin in tortor placerat, efficitur lacus ac, hendrerit tellus. Sed eu felis sed magna tincidunt cursus vel fermentum erat. Vivamus congue rhoncus velit, fringilla tempus mi volutpat eu. Donec eu malesuada odio. Praesent nec congue libero, ut feugiat odio. Aliquam volutpat, massa sed sodales ultricies, velit velit imperdiet justo, sit amet finibus est enim non lacus. Cras eu bibendum nunc. Duis sodales ligula et tincidunt blandit. Phasellus non luctus nisl. Nam vehicula risus ut nulla dapibus, ac interdum est consectetur. Pellentesque ac aliquet augue, id tempor nisl. Suspendisse potenti.</p>

            <p className="p-4 mb-6">Cras eget pulvinar risus. Phasellus blandit lectus a nisi pharetra congue. Mauris ornare nisi in pellentesque placerat. Fusce dignissim sem fringilla sapien sagittis tempus. Praesent vel fringilla turpis. Nulla facilisi. Integer faucibus metus tortor, sit amet aliquam ante tincidunt vitae. Mauris mattis a neque id fermentum. Nam cursus arcu a scelerisque blandit. Integer mollis in arcu quis finibus. Duis mattis, tortor vel fermentum rutrum, magna est malesuada odio, at porta mi ligula vel dui. Aliquam malesuada turpis eu dolor volutpat, in porttitor sapien dapibus.</p>

            <p className="p-4 mb-6">Donec aliquam porttitor hendrerit. Sed bibendum mauris velit, eu blandit ipsum condimentum ac. Suspendisse at auctor nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Sed tempus ultricies enim vitae efficitur. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris nec tincidunt tortor. Fusce faucibus congue lorem in bibendum. Donec vestibulum tincidunt mi, at posuere velit feugiat quis. Aliquam varius auctor magna a tincidunt. Donec in fermentum augue, quis volutpat nunc. Etiam metus lorem, ornare eu pellentesque in, tempor a augue. Vestibulum semper massa id odio bibendum, ac sollicitudin lacus bibendum.</p>
        </div>
    );
}

export default Contents;